---
name: TinyGo

on:
  push:
    branches: ["main", "tinygo-ci", update-build-constraints-2]
  pull_request:
    branches: [main]

env:
  FAILING:
    cmds/boot/boot
    cmds/boot/fitboot
    cmds/boot/pxeboot
    cmds/core/bind
    cmds/core/dhclient
    cmds/core/gosh
    cmds/core/init
    cmds/core/insmod
    cmds/core/io
    cmds/core/ip
    cmds/core/kexec
    cmds/core/lockmsrs
    cmds/core/msr
    cmds/core/netcat
    cmds/core/netstat
    cmds/core/nohup
    cmds/core/ping
    cmds/core/rmmod
    cmds/core/sluinit
    cmds/core/sshd
    cmds/core/switch_root
    cmds/core/tee
    cmds/core/watchdogd
    cmds/core/wget
    cmds/exp/console
    cmds/exp/esxiboot
    cmds/exp/fbnetboot
    cmds/exp/localboot
    cmds/exp/modprobe
    cmds/exp/netbootxyz
    cmds/exp/newsshd
    cmds/exp/pflask
    cmds/exp/pxeserver
    cmds/exp/systemboot
    cmds/exp/tcpdump
    cmds/exp/tftp
    cmds/exp/traceroute
    cmds/exp/uefiboot
    cmds/exp/vboot
    cmds/exp/vmboot

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.33.0'

      - name: Compile All and Check Expectation
        run: |

          go run tools/tinygoize/main.go \
            -o $GITHUB_STEP_SUMMARY \
            cmds/{core,exp,extra,boot}/*

          git diff-files --quiet
