---
name: TinyGo

on:
  push:
    branches: ["main", "tinygo-ci", update-build-constraints-2]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.33.0'

      - name: Run tinygoize
        run: |
          # tinygoize, check tree not dirty
          go build -C tools/tinygoize
          tools/tinygoize/tinygoize \
            -j 2 \
            -o $GITHUB_STEP_SUMMARY \
            cmds/{core,exp,extra,boot}/*

          git diff-files --quiet
