---
name: TinyGo-Dev

on:
  push:
    branches: [main, tinygo-dev-ci]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      # - uses: actions/setup-go@v4
      #   with:
      #     go-version: '1.23.x'

      - uses: actions/download-artifact@v4
        with:
          name: linux-amd64-double-zipped
          path: /tmp/foo
          # pattern:
          # merge-multiple:
          github-token: ${{ secrets.TINYGO_TOKEN }}
          repository: tinygo-org/tinygo
          run-id: 10920552472

      - name: ls
        run: |
          ls -alh /tmp/foo
          md5sum /tmp/foo/*
          dpkg -i /tmp/foo/*.deb
